### PR TITLE
docs: Remove redundant spaces in sample code

### PR DESCRIPTION
**Pull request by AndrewKeepCoding**
﻿## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] Tested the changes where applicable:
	- [ ] UWP
	- [ ] iOS
	- [ ] Android
	- [ ] WASM
	- [ ] MacOS
- [ ] Updated the documentation as needed:
	- [ ] [General Doc Update](https://github.com/unoplatform/Uno.Themes/tree/master/doc)
	- [ ] [material-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/material-controls-styles.md)
	- [ ] [cupertino-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/cupertino-controls-styles.md)
	- [ ] [lightweight-styling.md (LightWeight Styling Resource Keys)](https://github.com/unoplatform/Uno.Themes/blob/master/doc/lightweight-styling.md)
- [x] Contains **No** breaking changes
  > If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Review by carldebilly — APPROVED** [review]

**Review by kazo0 — APPROVED** [review]

**Comment by kazo0** [comment]
Woo!

image


Congrats on your first contribution to Uno.Themes! The first of many :)

**Comment by AndrewKeepCoding** [comment]
> The first of many :)

Yeah! The first of many!

**Comment by kazo0** [comment]
@AndrewKeepCoding FYI I see the Conventional Commits check is failing, we require the commit messages to follow a certain format, see: https://platform.uno/docs/articles/uno-development/git-conventional-commits.html/

You can amend your commit message to follow that pattern and it should be good to go!

**Comment by AndrewKeepCoding** [comment]
@kazo0 Sorry. I forgot to add the prefix. The link is broken by the way.

**Review by agneszitte — APPROVED** [review]

**Comment by agneszitte** [comment]
@Mergifyio backport release/stable/5.0

**Comment by agneszitte** [comment]
@Mergifyio backport release/stable/5.1

**Comment by agneszitte** [comment]
@AndrewKeepCoding thank you for the contribution 😊

**Comment by AndrewKeepCoding** [comment]
Sorry for the mess. 😵

**Pull request merged**
