### PR TITLE
refactor: check for missing explicit and implicit v2 styles

### PR DESCRIPTION
**Pull request by silviuo**
﻿GitHub Issue: closes unoplatform/private#331

## PR Type
What kind of change does this PR introduce?
- Refactoring (no functional changes, no api changes)

## Description
This PR refactors Uno.Themes v2 controls to make sure all of them include default explicit/implicit styles.

This file contains the code I used to test the styles and also in-app screenshots for the visual comparison for the three styles - the style that was used as default before the changes, the new default and the new default implicit:
[Styles test.docx](https://github.com/unoplatform/Uno.Themes/files/11959112/Styles.test.docx)

## PR Checklist 
Please check if your PR fulfills the following requirements:
- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [X] Tested UWP
- [ ] Tested iOS
- [ ] Tested Android
- [X] Tested WASM
- [ ] Tested MacOS
- [x] Contains **No** breaking changes
  > If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by Xiaoy312** [comment]
Could you repost the content of Control issues.docx as a new issue?

**Review by kazo0 — APPROVED** [review]

**Review by agneszitte — APPROVED** [review]

**Comment by agneszitte** [comment]
> Could you repost the content of Control issues.docx as a new issue?

@silviuo you can repost the details of the docx here in the related issue https://github.com/unoplatform/private/issues/331

**Comment by silviuo** [comment]
> Could you repost the content of Control issues.docx as a new issue?

I removed the file. I also wasn't able to repro any of the issues in a sample app using the latest dependency versions, nor in the canaries playground where applicable.

**Comment by silviuo** [comment]
Rebased off of main

**Comment by agneszitte** [comment]
https://github.com/Mergifyio backport legacy/2x

**Pull request merged**
