### PR TITLE
 Fixed duplicate word in themes-overview.md

### PR DESCRIPTION
**Pull request by sfazli96**
﻿GitHub Issue: #

## PR Type

What kind of change does this PR introduce?
Just refactoring a sentence/code update formatting, repeated word include to including

## Description

The change was that in themes-overviews.md I updated the sentence from a repeated word to just one-word fix.

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [x] Tested the changes where applicable:
	- [x] UWP
	- [x] iOS
	- [x] Android
	- [x] WASM
	- [x] MacOS

### CODE REVIEW

**Review by agneszitte — APPROVED** [review]

**Comment by agneszitte** [comment]
@sfazli96 thank you a lot for your PR, I approved the changes.
As I mentioned [here](https://github.com/unoplatform/Uno.Themes/issues/1274#issuecomment-1802215922), your commit **must** be in the [Conventional Commits format](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/git-conventional-commits.md) please.
image
So if you can update and replace your current commit with a similar commit message please:
```diff
- fixed repeated word include twice to including in themes-overview.md
+ docs: Fixed duplicate word in themes-overview.md
```

**Comment by kazo0** [comment]
@sfazli96 thanks for the PR!

It looks like the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) check is still failing because you need to prefix your commit message with an appropriate _type_, such as `fix:` or `docs:`

**Comment by sfazli96** [comment]
ok, I see so do i have to make another commit, that's where I am just a little confused. Please explain

**Comment by agneszitte** [comment]
> ok, I see so do i have to make another commit, that's where I am just a little confused. Please explain

@sfazli96 you will need to adjust the current commit (as conventional commit will still fail if there is still a commit without the proper prefix). Here is the related documentation so you can learn how to adjust your commit message :)
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

Let us know if you have additional questions

**Review by iurycarlos — APPROVED** [review]

**Comment by agneszitte** [comment]
@sfazli96 gentle ping for this PR. Please let @iurycarlos or me know if you still need help adjusting your commit so we can merge the changes. Thanks again for your contribution

**Comment by iurycarlos** [comment]
Ok! @sfazli96 !
I created a new PR so you can compare both.
It is the same fix, but with just one commit.
The commit title is now following Conventional Commits https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by Darsh0307** [comment]
This PR got closed Automatically because the PR (https://github.com/unoplatform/Uno.Themes/pull/1308) was merged  
Thank you very much @sfazli96  :)

**Pull request closed without merging**
