### PR TITLE
docs: terminology corrections

### PR DESCRIPTION
**Pull request by mikeirvingweb**
docs: Corrections to MacOS and .NET branding

### CODE REVIEW

**Comment by kazo0** [comment]
Thanks for the contribution @mikeirvingweb 👍 

Looks like this PR is currently blocked by the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) check. 

You can also check out the documentation surrounding how to format conventional commits for this repo:
https://platform.uno/docs/articles/uno-development/git-conventional-commits.html

**Comment by mikeirvingweb** [comment]
Thanks @kazo0. I am new to this sort of thing. I think it is conventional now.

**Comment by mikeirvingweb** [comment]
@jeromelaban does the build need to be kickstarted again, or will that happen automatically?

/azp run

**Comment by jeromelaban** [comment]
You need to change the commit's text to use conventional commits convention (changing the PR title is not enough)

**Comment by kazo0** [comment]
@mikeirvingweb You can check out the [PR Guidelines](https://platform.uno/docs/articles/contributing/guidelines/pull-requests.html#updating-your-branch-on-top-of-the-latest-of-the-default-branch) primarilly the part that talks about "Squash your commits, using interactive rebase"

Basically, you'll need to rebase and squash your commits into a single commit and rename that new commit following the conventional commits, something like "docs: terminology corrections"

I'm trying to find a guide somewhere that isn't totally confusing, you can take a look at this (https://linuxize.com/post/change-git-commit-message/#changing-an-older-or-multiple-commits)

In that guide, instead of doing `git rebase -i HEAD~5`, you can first call `git fetch origin master` and then `git rebase origin/master -i`

**Comment by mikeirvingweb** [comment]
2 failures over on DevOps, that I can see  

azure-pipelines
/ Uno.Themes - CI
Build log #L6780
Error: The process '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild' failed with exit code 1  

can those be resolved manually @jeromelaban?

**Pull request merged**
