### PR TITLE
fix(ToggleSwitch): Override ToggleSwitch MinWidth

### PR DESCRIPTION
**Pull request by eriklimakc**
﻿GitHub Issue: #1225

## PR Type

What kind of change does this PR introduce?
- Bugfix

## Description
Added `<x:Double x:Key="ToggleSwitchThemeMinWidth">0</x:Double>` and `<Setter Property="MinWidth" Value="{ThemeResource ToggleSwitchThemeMinWidth}" />` to prevent the extra `MinWidth="154"` from stretching the control.

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] Tested the changes where applicable:
	- [X] UWP
	- [X] iOS
	- [X] Android
	- [X] WASM
	- [X] GTK
	- [ ] MacOS
- [ ] Updated the documentation as needed:
	- [ ] [General Doc Update](https://github.com/unoplatform/Uno.Themes/tree/master/doc)
	- [ ] [material-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/material-controls-styles.md)
	- [ ] [cupertino-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/cupertino-controls-styles.md)
	- [ ] [lightweight-styling.md (LightWeight Styling Resource Keys)](https://github.com/unoplatform/Uno.Themes/blob/master/doc/lightweight-styling.md)
- [ ] Contains **No** breaking changes
  > If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Review by kazo0 — APPROVED** [review]

**Review by iurycarlos — APPROVED** [review]

**Review by Youssef1313 — COMMENTED** [review]
The problem here is that this will be a problem with the same sample if fluent theme is used instead of Cupertino/Material.

**Comment by eriklimakc** [comment]
> The problem here is that this will be a problem with the same sample if fluent theme is used instead of Cupertino/Material.

Yes, but we need this for the Figma Plugin release.

So I created this issue (https://github.com/unoplatform/uno/issues/13946) on Uno Core repo for us to track/fix later, and I'm sure it would take more discussion on what should be done.

I will add this link to the Material/Cupertino styles for us to know why we have the `MinWidth` set.

cc @kazo0 @Youssef1313 @agneszitte @iurycarlos @Xiaoy312

**Comment by Youssef1313** [comment]
Problem is, there is really nothing to fix on Uno side as we're matching WinUI :'(
One option could be for AutoLayout itself to figure out that a ToggleSwitch is at the very right and then explicitly set MinWidth to zero, but that is very very hacky.

For now, I'm fine for the change being specific to Material/Cupertino

**Comment by agneszitte** [comment]
I have left a comment on the other issue
https://github.com/unoplatform/uno/issues/13946#issuecomment-1755937355

**Pull request merged**
