### PR TITLE
fix: corrected m3 ContentDialog style

### LINKED ISSUE #637: [Material] Add ContentDialog
## What would you like to be added:

Investigation needs to be done to see how customizable is the ContentDialog. We would need the ability to customize the "chrome" surrounding the Content part. So the action button areas as well as CornerRadius, etc.

Material style for ContentDialog

UWP:
image

Material:
image

Material Guidance:
https://m3.material.io/components/dialogs/overview

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

### PR DESCRIPTION
**Pull request by Xiaoy312**
﻿GitHub Issue: closes #637

## PR Type

What kind of change does this PR introduce?
- Bugfix

## Description
[corrected m3 ContentDialog style](fix: corrected m3 ContentDialog style)

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [x] Tested UWP
- [ ] Tested iOS
- [ ] Tested Android
- [ ] Tested WASM
- [ ] Tested MacOS
- [x] Contains **No** breaking changes
  > If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by kazo0** [comment]
Looks good!

**Review by kazo0 — APPROVED** [review]

**Comment by kazo0** [comment]
Actually, is the dialog content text foreground supposed to be gray? Kinda looks like it's disabled

**Comment by kazo0** [comment]
Actually it's not that much of a change but might be worth looking into.

Left Dialog is OnSurfaceVariant

**Comment by NVLudwig** [comment]
> It's not that much of a change but might be worth looking into. @NVLudwig
> 
> Left Dialog is OnSurfaceVariant 

Yeah I think you are screen shooting that from an old file or something else. 

This is the branch with the latest component:
https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/branch/M6OAII7QrUlUdQCvw5LeGK/Uno-Platform-Material-Toolkit-R2?node-id=3082%3A106932

The Title and Body use different colors and the body should be OnSurfaceVariant as per the specs.

**Comment by kazo0** [comment]
> > It's not that much of a change but might be worth looking into. @NVLudwig
> > 
> > Left Dialog is OnSurfaceVariant 
> 
> Yeah I think you are screen shooting that from an old file or something else. 
> 
> @kazo0  This is the branch with the latest component:
> https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/branch/M6OAII7QrUlUdQCvw5LeGK/Uno-Platform-Material-Toolkit-R2?node-id=3082%3A106932
> 
> The Title and Body use different colors and the body should be OnSurfaceVariant as per the specs.
> 
> <blockquote><div> Figma</div><div><strong><a href="https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/branch/M6OAII7QrUlUdQCvw5LeGK/Uno-Platform-Material-Toolkit-R2?node-id=3082%3A106932">Figma</a></strong></div></blockquote>

Ah ok then @Xiaoy312 maybe we need to double check that the latest Figma file is the one that was referenced when implement this style

**Comment by Xiaoy312** [comment]
double checks: 
- [ ] content brush
- [ ] overlay brush

**Review by NVLudwig — APPROVED** [review]

**Comment by NVLudwig** [comment]
New examples look much better

**Pull request merged**
